[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = """
  if [ "$PROJECT_TYPE" == "backend" ]; then
    uvicorn backend.main:app --host 0.0.0.0 --port 8501;
  elif [ "$PROJECT_TYPE" == "frontend" ]; then
    streamlit run frontend/main.py --server.port=8000 --server.enableCORS false --server.enableXsrfProtection false;
  else
    echo "Erro: variável PROJECT_TYPE não definida.";
  fi
"""
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
