[global]
disableWidgetStateDuplicationWarning = true  # Evita alertas desnecessários

[server]
enableCORS = false
enableXsrfProtection = false
runOnSave = true  # Reinicia automaticamente ao salvar mudanças

[browser]
gatherUsageStats = false  # Impede o envio de dados para o Streamlit